@startuml
state Laptop {
  [*] -> Charging
  Charging -> OnBattery 
  OnBattery -> Charging 
  --
  [*] -> LidOpen
  LidOpen -> LidClosed 
  LidClosed -> LidOpen
  --
  [*] -> Sleeping
  Sleeping -> Working 
  Working -> Sleeping 
}
@enduml