/*
 * Author: Mikhail Fedotov
 * Github: https://github.com/KStateMachine
 * Copyright (c) 2024.
 * All rights reserved.
 */

package ru.nsk.kstatemachine.event

import ru.nsk.kstatemachine.state.DataState
import ru.nsk.kstatemachine.state.FinalDataState
import ru.nsk.kstatemachine.state.IState
import ru.nsk.kstatemachine.state.joinDataTransition
import ru.nsk.kstatemachine.statemachine.StateMachine
import ru.nsk.kstatemachine.statemachine.undo

/**
 * Base interface for events which may trigger transitions of [StateMachine]
 * Events are expected to be immutable subjects by design.
 */
interface Event

/**
 * Event holding some data
 */
interface DataEvent<out D : Any> : Event {
    val data: D
}

/**
 * User may call [StateMachine.processEvent] with [UndoEvent] as alternative to calling [StateMachine.undo]
 */
object UndoEvent : Event

/**
 * Marker interface for all events that are generated by the library itself
 */
sealed interface GeneratedEvent : Event

/**
 * Special event generated by the library when a state is finished.
 * Transitions use special event matcher by default to match only related events.
 * If [FinishedEvent] is generated by [FinalDataState] entry, [data] field of event will receive data
 * from this state using [DataExtractor]
 */
class FinishedEvent internal constructor(val state: IState, val data: Any? = null) : GeneratedEvent

/**
 * Initial event which is processed on state machine start
 */
sealed interface StartEvent : GeneratedEvent {
    val startState: IState
}

/**
 * [startStates] must contain at least one state. If there are multiple states they must be sub-children of a parallel
 * state.
 */
internal class StartEventImpl(val startStates: Set<IState>) : StartEvent {
    override val startState = startStates.first()
}

internal class StartDataEventImpl<D : Any>(
    override val startState: DataState<D>,
    override val data: D
) : StartEvent, DataEvent<D>

internal object StopEvent : GeneratedEvent

/**
 * This event is processed even if the [StateMachine] is already stopped
 */
internal class DestroyEvent(val stop: Boolean) : GeneratedEvent

/**
 * System event which is used by the library to wrap original event and argument,
 * so user may access them, when this event is processed.
 * Currently only [UndoEvent] is transformed to this event.
 * @param event original event
 * @param argument original argument
 */
class WrappedEvent(val event: Event, val argument: Any?) : GeneratedEvent

/**
 * Special kind of event, which is not processed by a stateMachine itself but used to
 * represent different kinds of [GeneratedEvent] in serialized form for event recording feature.
 */
data class SerializableGeneratedEvent(val eventType: EventType) : GeneratedEvent {
    sealed interface EventType {
        object Start : EventType
        object Stop : EventType
        class Destroy(val stop: Boolean) : EventType
    }
}

/** Internal event fired when all join-point states become simultaneously active. */
interface JoinCompleteEvent : GeneratedEvent {
    val transitionId: Any
}

interface JoinCompleteDataEvent<D : Any> : JoinCompleteEvent, DataEvent<D>

internal data class JoinCompleteEventImpl(override val transitionId: Any) : JoinCompleteEvent

/** Internal data-carrying variant of [JoinCompleteEvent], used by [joinDataTransition]. */
internal data class JoinCompleteDataEventImpl<D : Any>(
    override val transitionId: Any,
    override val data: D,
) : JoinCompleteDataEvent<D>

/**
 * Event automatically generated by the library to fire an eventless (UML "always") transition
 * on state entry. Each registration of [autoTransition] is paired with a unique [transitionId]
 * so multiple eventless transitions from the same source state do not collide.
 */
interface AutoEvent : GeneratedEvent {
    val transitionId: Any
}

interface AutoDataEvent<D : Any> : AutoEvent, DataEvent<D>

internal data class AutoEventImpl(override val transitionId: Any) : AutoEvent

/** Internal data-carrying variant of [AutoEvent], used by `automaticDataTransition`. */
internal data class AutoDataEventImpl<D : Any>(
    override val transitionId: Any,
    override val data: D,
) : AutoDataEvent<D>

/**
 * Event automatically generated by the library to fire a delayed (UML "after Xms") transition
 * once the configured delay elapses while the source state is active. Each registration of
 * `delayedTransition` is paired with a unique [transitionId].
 *
 * Lives in core so that [GeneratedEvent] (a sealed interface) stays exhaustive — the actual
 * DSL that emits these events lives in `kstatemachine-coroutines`.
 */
interface DelayedTransitionEvent : GeneratedEvent {
    val transitionId: Any
}

/**
 * Library-internal. Public only because it has to be constructable from `kstatemachine-coroutines`
 * (Kotlin `internal` is per-module). Do not construct directly in user code.
 */
data class DelayedTransitionEventImpl(
    override val transitionId: Any,
) : DelayedTransitionEvent

/**
 * Library-internal data-carrying variant of [DelayedTransitionEvent], used by `delayedDataTransition`.
 * Public for the same cross-module reason as [DelayedTransitionEventImpl].
 */
data class DelayedTransitionDataEventImpl<D : Any>(
    override val transitionId: Any,
    override val data: D,
) : DelayedTransitionEvent, DataEvent<D>
