title: KStateMachine
description: KStateMachine is a Kotlin DSL library for creating state machines and statecharts.
url: https://kstatemachine.github.io/kstatemachine/

aux_links:
  KStateMachine on GitHub: https://github.com/KStateMachine/kstatemachine

theme: just-the-docs
color_scheme: dark

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.1"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple